<?php

/**
 * @file
 * Contains open_farm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function open_farm_dashboard_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the open_farm_dashboard module.
        case 'help.page.open_farm_dashboard':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Displays Open Farm visualizations and other important information.') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function open_farm_dashboard_theme($existing, $type, $theme, $path) {
    return [
        'open_farm_dashboard' => [
            'template' => 'open_farm_dashboard',
            'variables' => array('viz_data' => NULL),
        ],
    ];
}
function open_farm_dashboard_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    $currentUser = Drupal::currentUser();
    $roles = $currentUser->getRoles();
    print_r($roles);

    if ($form_id == 'user_login_form' && !in_array('dashboard', $roles)){
        $form['#submit'][] = 'open_farm_dashboard_user_login_form_submit';
    }
}
function open_farm_dashboard_user_login_form_submit($form, FormStateInterface $form_state){
    $form_state->setRedirect('open_farm_dashboard.dashboard');
}